name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_CONFIG: Release
  WEB_CSPROJ_PATH: ${{ github.workspace }}\src\TestActionsApi.Web\TestActionsApi.Web.csproj
  WEB_PUBLISH_PATH: ${{ github.workspace }}\published

jobs: 
  Build:
    runs-on: windows-latest
      
    steps:        
    - name: Checkout
      uses: actions/checkout@v2
 
    - name: Install dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
 
    -  name: Restore    
       run: dotnet restore
 
    - name: Build  
      run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIG }}
 
    - name: Test
      run: dotnet test --no-restore
     
    - name: Publish
      run: dotnet publish ${{ env.WEB_CSPROJ_PATH }} --no-build --configuration ${{ env.BUILD_CONFIG }} --output ${{ env.WEB_PUBLISH_PATH }}
    
    - name: Uplaod
      uses: actions/upload-artifact@v2
      with:
        name: gha-testing-bin
        path: ${{ env.WEB_PUBLISH_PATH }}\
      
