name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_CONFIG: Release
  WEB_CSPROJ_PATH: ${{ github.workspace }}\src\TestActionsApi.Web\TestActionsApi.Web.csproj
  WEB_PUBLISH_PATH: ${{ github.workspace }}\published
  WEB_ZIP_PATH: ${{ github.workspace }}\published.zip
  ARTIFACT_DOWNLOAD_PATH: ${{ github.workspace }}/artifact
  ARTIFACT_ZIP_PATH: ${{ github.workspace }}/artifact/published.zip

jobs: 
  Build:
    runs-on: windows-latest
      
    steps:        
    - name: Checkout
      uses: actions/checkout@v2
 
    - name: Install dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
 
    -  name: Restore    
       run: dotnet restore
 
    - name: Build  
      run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIG }}
 
    - name: Test
      run: dotnet test --no-restore
     
    - name: Publish
      run: dotnet publish ${{ env.WEB_CSPROJ_PATH }} --no-build --configuration ${{ env.BUILD_CONFIG }} --output ${{ env.WEB_PUBLISH_PATH }}
    
    - name: Zip
      run: Compress-Archive -Path ${{ env.WEB_PUBLISH_PATH }} -DestinationPath ${{ env.ARTIFACT_ZIP_PATH }}
    
    - name: Uplaod
      uses: actions/upload-artifact@v2
      with:
        name: gha-testing-build
        path: ${{ env.WEB_PUBLISH_PATH }}\

  Store:
      needs: Build
      runs-on: ubuntu-latest
      
      steps:
        - name: Download
          uses: actions/download-artifact@v2
          with:
            name: gha-testing-build
            path: ${{ env.ARTIFACT_DOWNLOAD_PATH }}

        - name: Authenticate
          uses: azure/login@v1.1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            
        - name: Upload
          uses: azure/cli@v1.0.0
          with:
            inlineScript: az storage blob upload --account-name ghaartifacts --container-name root --file ${{ env.ARTIFACT_ZIP_PATH }} --name ${{ github.sha }}

        - name: Logout
          uses: azure/cli@v1.0.0
          with:
            inlineScript: az logout
